sudo: false
dist: trusty
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

addons:
    postgresql: "9.6"
services:
    - postgresql

install:
  - pip install mongo-orchestration==0.6.7
  - pip install flake8

before_script:
  - flake8 .
  - mongo-orchestration -b 127.0.0.1 start

script:
  - python setup.py test

after_script:
  - mongo-orchestration stop
